#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# supprImage:
#     path: /admin/supprImage
#     controller: App\Controller\DefaultController::AdminController
#     methods: [DELETE]


     
 
